# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: tonicorreal
  email_provider_password: kpbpv677
  domain_name: example.com
  mailchimp_api_key: '4d486f30e31e1006031c566674a51d42-us13'
  mailchimp_list_id: 882d1d1449
  owner_email: tonicorreal@gmail.com
  secret_key_base: 05293ce44ea2b90246eec377c7a9f4798c9727e0e16fba94f4477ff58a07bb83b29376f633f64c17950dc8dd72e4747cfa671a67f30ac632a9c2758f226a6dc8

test:
  secret_key_base: c5040fb14648e3bb659da09ca260d562e7e46e5a70756f40f5c99164e095657513e32d5533716d4dce66ec546294df5099f0096a014becceff352436cc8f9d72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: tonicorreal
  email_provider_password: kpbpv677
  domain_name: example.com
  mailchimp_api_key: '4d486f30e31e1006031c566674a51d42-us13'
  mailchimp_list_id: 882d1d1449
  owner_email: tonicorreal@gmail.com
  secret_key_base: 05293ce44ea2b90246eec377c7a9f4798c9727e0e16fba94f4477ff58a07bb83b29376f633f64c17950dc8dd72e4747cfa671a67f30ac632a9c2758f226a6dc8
